class aboutUser
	def greet(name)
    	puts "Hello, #{name}."
    	puts "How are you?"
    	puts "..."
    	puts "Well then..."
	end

	def response(userState)
    	puts "..."
    	puts "..."
    	puts "Huh..."
		puts "#{userState}?"
    	puts "Everything is dark"
    	puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "dark..."
		puts "it's dark... Where am I? Who am I? Is anyone there?"
	end
end

puts greet(Qunaqa)
puts response(Bloody)